<?php

//For the genre links on the individual movie pages
/**
 * Implements hook_node_view
 */
function movie_layout_node_view($node, $view_mode, $langcode) {

    if ($node->type == 'movie_review' && $view_mode == 'full'){

        $links = array();

        foreach ($node->field_movie_review_genre as $key => $value){
            foreach ($value as $k => $term){

                // Load the taxonomy term
                $taxonomy_term = taxonomy_term_load($term['tid']);

                // Create the links
                $links[] = l($taxonomy_term->name, 'reviews/' . $taxonomy_term->name);

                //dsm($taxonomy_term);
            }
        }

        //dpm($links);

        $node->content ['genre_links'] = array(
            '#markup' => theme('item_list',
                array(
                    'items' => $links,
                    'title' => 'Genres',
                    'attributes' => array('class' => 'genre-taxonomy-list'))
            ),
            '#weight' => 10,
        );
    }
}

//for the breadcrumbs
/**
 * Implements hook_preprocess_page
 */

//function movie_layout_preprocess_page(&$vars){
//    $object = menu_get_item();
//
//    $links = array();
//
//    dsm($object);
//    // if the current page is a view page and we are looking at the url reviews/genre
//    if ($object['page_callback'] == 'views_page' && strstr($object['href'], 'reviews')){
//        $links = array(
//            l('Home', '<front>'),
//            l('Reveiws', 'Reviews' ),
//        );
//
//        //if an argument has been passed to the view
//        if (!empty($object['map'][1])) {
//            $links[] = $object['map'][1];
//        }
//    }
//
//    $node = menu_get_object();
//
//    // if we are looking at a Movie Review content type
//    if (!empty($node) && node_is_page($node) && $node->type == 'movie_review'){
//        //dsm($node);
//        $links = array(
//           l('Reveiws', 'reviews' ),
//           $node->title,
//        );
//    }
//
//
//    // if custom links have been defined for this breadcrumb. set it.
//    if (!empty($links)){
//       drupal_set_breadcrumb($links);
//    }
//
//}

//simplyfied from above
function movie_layout_preprocess_page(&$vars){
    $object = menu_get_item();
    $node = menu_get_object();

    $links = array();

    //if the object exists and is a node page
    if (!empty($node) && node_is_page($node)) {
        $content_types = array(
            'movie_review' => 'reviews',
            'news_' => 'news',
            'top_ten_films' => 'Top Ten Lists',
    );

    // defines the first link which appears on all content types
     $links[] = l('Home', '<front>');

        // for each breadcrumb trail definition
        foreach ($content_types as $machine_name => $title) {
            if ($node->type == $machine_name) {
                // create the link as defined to the view
                $links[] = l($title, strtolower(str_replace(' ', '-', $title)));
                // append the node title
                $links[] = $node->title;
            }
        }
    }

    // if custom links have been defined for this breadcrumb. set it.
    if (!empty($links)){
        drupal_set_breadcrumb($links);
    }

}